from pathlib import Path
import hashlib,sys
ROOT=Path(__file__).resolve().parent
items={
    'package/validation_framework/wave_a/batch_0001_0005/manufacturer_evidence_sources.csv': 'component_id,manufacturer,model,proposed_sku,source_url,source_type,claim_scope,evidence_status,access_date\nCMP-LDR-0001,SICK,TiM571,TiM571-2050101,https://www.sick.com/media/pdf/4/44/444/dataSheet_TiM571-2050101_1075091_en.pdf,manufacturer_datasheet,2D planar; specific variant TiM571-2050101; not a machine-safety component,model_specific_evidence,2026-10-09\nCMP-LDR-0002,Hokuyo,UST-10LX,UST-10LX,https://www.hokuyo-aut.jp/search/single.php?serial=167,manufacturer_product_spec,2D scanning; 270 deg; 0.06-10m white target; 0.06-4m at 10% reflectance,model_specific_evidence,2026-10-09\nCMP-LDR-0003,SLAMTEC,RPLIDAR S2,S2M1-Rx,https://www.slamtec.com/en/s2/spec,manufacturer_product_spec,S2 0.05-30m at 90% reflectance; 0.05-10m at 10%; Rx requires variant resolution,model_variant_pending,2026-10-09\nCMP-LDR-0004,Ouster,OS1,,https://static.ouster.dev/sensor-docs/hw_user_manual_OS1/hw_common_sections_OS1/os1-overview.html,manufacturer_hardware_manual,OS1 Rev7 family includes OS1-32 OS1-64 OS1-128; no exact SKU selected,family_only,2026-10-09\nCMP-LDR-0005,Livox,Mid-360,Mid-360,https://www.livoxtech.com/de/mid-360/specs,manufacturer_product_spec,905nm; 40m at 10% reflectivity 100klx; H360 V59; 200k points/s; 10Hz; IP67,model_specific_evidence,2026-10-09\n',
    'package/validation_framework/wave_a/batch_0001_0005/manufacturer_evidence_claims.csv': 'component_id,claim_key,claim_value,conditions_or_scope,source_url,claim_verification,device_test_status\nCMP-LDR-0001,variant_identity,TiM571-2050101,manufacturer datasheet,https://www.sick.com/media/pdf/4/44/444/dataSheet_TiM571-2050101_1075091_en.pdf,source_backed,not_tested\nCMP-LDR-0002,range_white_target,0.06-10 m,white Kent sheet,https://www.hokuyo-aut.jp/search/single.php?serial=167,source_backed,not_tested\nCMP-LDR-0002,range_10pct,0.06-4 m,diffuse reflectance 10%,https://www.hokuyo-aut.jp/search/single.php?serial=167,source_backed,not_tested\nCMP-LDR-0002,horizontal_fov,270 deg,manufacturer specification,https://www.hokuyo-aut.jp/search/single.php?serial=167,source_backed,not_tested\nCMP-LDR-0003,range_90pct,0.05-30 m,S2 variant,https://www.slamtec.com/en/s2/spec,source_backed,not_tested\nCMP-LDR-0003,range_10pct,0.05-10 m,S2 variant,https://www.slamtec.com/en/s2/spec,source_backed,not_tested\nCMP-LDR-0003,sample_rate,32000 samples/s,S2 variant,https://www.slamtec.com/en/s2/spec,source_backed,not_tested\nCMP-LDR-0004,family_variants,OS1-32 / OS1-64 / OS1-128,Rev7 manual; not a specific SKU,https://static.ouster.dev/sensor-docs/hw_user_manual_OS1/hw_common_sections_OS1/os1-overview.html,source_backed,not_tested\nCMP-LDR-0005,range_10pct,40 m,100 klx,https://www.livoxtech.com/de/mid-360/specs,source_backed,not_tested\nCMP-LDR-0005,fov,360 x 59 deg,horizontal x vertical,https://www.livoxtech.com/de/mid-360/specs,source_backed,not_tested\nCMP-LDR-0005,point_rate,200000 points/s,first return,https://www.livoxtech.com/de/mid-360/specs,source_backed,not_tested\nCMP-LDR-0005,ip_rating,IP67,manufacturer spec,https://www.livoxtech.com/de/mid-360/specs,source_backed,not_tested\n',
    'package/validation_framework/wave_a/batch_0001_0005/MANUFACTURER_EVIDENCE_REVIEW.md': '# Wave 1 Manufacturer Evidence Review — 2026-10-09\n\nThis is a non-destructive evidence supplement to initial Wave 1 candidate records. Source-backed claims do NOT imply physical testing, certification, availability, or qualified integration.\n\n- CMP-LDR-0001: SICK TiM571-2050101 model-specific manufacturer datasheet found. Confirm the intended exact SKU before changing the original identity.\n- CMP-LDR-0002: Hokuyo UST-10LX model-specific manufacturer page found. Model can be marked `listed` after identity review.\n- CMP-LDR-0003: SLAMTEC RPLIDAR S2 product variant supported, but S2M1-Rx has an unresolved x subvariant; preserve distinction from S2L/S2P/S2E.\n- CMP-LDR-0004: Ouster OS1 is a FAMILY with OS1-32, OS1-64 and OS1-128 and hardware revisions; do not claim a unique SKU or model-specific verified specs.\n- CMP-LDR-0005: Livox Mid-360 model-specific specs found; do not conflate with Mid-360L.\n\n**Status:** manufacturer evidence collected for 5/5 families/models; 0/5 hardware tested; SKU closure pending for 0001/0003/0004. This patch deliberately leaves the original inventory and master catalog untouched until approval of identity normalization.\n\nAlgorithm support, ROS2 driver compatibility, EOL, stock, pricing, and physical qualification are **not tested/not independently verified** by this patch.\n',
 }
# Paths are relative to repository root; source ZIP uses package/ prefix.
for key,content in items.items():
    dest=ROOT/key.removeprefix('package/')
    if dest.exists() and dest.read_text(encoding='utf-8-sig')!=content:
        sys.exit('CONFLICT: existing content differs: '+str(dest))
for key,content in items.items():
    dest=ROOT/key.removeprefix('package/')
    dest.parent.mkdir(parents=True,exist_ok=True)
    if not dest.exists(): dest.write_text(content,encoding='utf-8',newline='\n')
print('SUCCESS: Manufacturer evidence supplement integrated (5 devices; no physical testing)')
